import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { TypewriterEffectSmoothDemo } from "@/components/Name";
import { Spotlight } from "@/components/ui/Spotlight";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Adobe GenSolve",
  description: "Generated by Harshit Shrivastav",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="relative w-full flex items-center justify-center">
          {/* <TypewriterEffectSmoothDemo /> */}

          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
}
